[build]
  publish = "."
  functions = "functions/"

[functions]
  [functions.server]
    server = "functions/server.js"
    handler = "server.handler"

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/server"

[[redirects]]
  from = "/socket.io"
  to = "/.netlify/functions/server"